### PR TITLE
Make commands for project generation and CLI build

### PR DESCRIPTION
**Pull request by rinat-enikeev**
Implements Makefile for project generation with SPM and Frameworks. 

## Steps to gather statistics

```bash
make xcodeproj_with_frameworks
make build_with_frameworks

make xcodeproj_with_spm
make build_with_spm

make build_with_pods
```

Build statistics for **warmed cache**, build time in seconds: 

| | Pods | SPM | Frameworks |
| ---- | ---- | ---- | ---- |
| CLI | 27 | 70 | 84 |
| Xcode | 15.6 | 21.4 | 28 |
| Second | 7.5 | 0.3 | 0.3 |
| Incremental | 9.3 | 1.7 | 1.2 |

Where CLI is xcodebuild, Xcode is build from Xcode, Second is second sequential build from Xcode, Incremental is build after adding `print` statement inside module.

### CODE REVIEW

**Comment by rinat-enikeev** [comment]
On my machine: 

`make build_with_spm` with deleted `Derived Data` took **493 seconds**  [66.7 MB app / 357,9 MB folder].
`make build_with_frameworks` with deleted `Derived Data` took **484 seconds** [76,7 MB app / 431,9 folder].

`make build_with_pods` with deleted `Derived Data` after pod install took 128 seconds [79,9 MB app / 437,6 MB folder]

**Comment by rinat-enikeev** [comment]
IPA:
- SPM 30,5 MB
- Frameworks 35.3 MB
- Pods 37.3 MB

**Comment by rinat-enikeev** [comment]
Screenshot 2023-11-24 at 21 55 20

**Comment by rinat-enikeev** [comment]
Note: Pods IPA is bigger because of extensions. 

Screenshot 2023-11-24 at 21 57 43

**Review by priyonto — APPROVED** [review]

**Comment by priyonto** [comment]
@rinat-enikeev Usually I would prefer to go with SPM but looking at the build time with pods makes me curious how its significantly lower than SPM. Do you have an M1 machine or Intel?

**Comment by rinat-enikeev** [comment]
> @rinat-enikeev Usually I would prefer to go with SPM but looking at the build time with pods makes me curious how its significantly lower than SPM. Do you have an M1 machine or Intel?

M1 Max. SPM/frameworks Incremental build are better than Pods. 

Fresh builds are downloading all packages, while Pods doesn't count `pod install` download operation.

**Pull request merged**
