### PR TITLE
Add battery level check on FW upgrade from Discover

### PR DESCRIPTION
**Pull request by rinat-enikeev**
Implements battery charge check on Firmware upgrade process on Discover

### CODE REVIEW

**Comment by DG12** [comment]
I am confused about the test ( I'm not too swift when it comes to Swift. May be I just need a coffee.). 
<pre>batteryNeedsReplacement(
 Bool {
         if let temperature = ruuviTag.celsius,
             let voltage = ruuviTag.volts {
             if temperature < 0, temperature >= -20 {
                 voltage < 2.3
             } else if temperature < -20 {
                 voltage < 2
             } else {
                 voltage < 2.5
             }
         } else {
             false
         }
     }
)
</pre>



It seems to be

Between -20C : 0C  it is cold , voltage should be more than 2.3v   (Is my understanding correct?? Would the range operator "..." be better??)

Colder than -20C  best case?? , voltage should be more than 2.0v ( Does not seem correct to me)

else(otherwise) if the voltage is below 2.5 true i.e. replace

<pre>
-20..0  ;;  ??    ;; -20 ..warm
at 2.3       2.5         2.0
least</pre>

This expects the power supply is via (the most likely) CR2477. 

Prudence may suggest replacing the battery anyway if easily accessible.
Your actual milage may vary.

**Comment by rinat-enikeev** [comment]
@DG12 interesting question. I've taken it blindly from `master` https://github.com/ruuvi/com.ruuvi.station.ios/blob/master/station/Extensions/Structs/RuuviTagBatteryStatusProvider.swift branch. 

@ojousima @priyonto do you have a source of this logic?

**Comment by priyonto** [comment]
I think @laurijamsa would probably the best person who can explain this. If I remember correctly this is the logic we followed on all platforms and there's no way to get this value accurately all the time, and this returns an approximation of the battery level instead.

**Comment by DG12** [comment]
Not being swift programmer I don't understand the code.
Especially the
<pre> if temperature < 0, temperature >= -20 {
voltage < 2.3
}</pre> ...

**Comment by priyonto** [comment]
@DG12 If you are interested in the logic check this card: https://github.com/ruuvi/com.ruuvi.station.ios/issues/836

**Comment by DG12** [comment]
Additional thoughts:
Since the voltage is at the current temperature of the battery, is it really necessary to have various tests for different temperatures?

That is:
Case1 : GOOD: The battery is at room temperature and greater than 2.0v (maybe even 1.9).
Case2 : GOOD: The battery is cold and is still greater than 2.0v .
Case3 : GOOD: The battery is really cold and still greater than 2.0v

Therefore only ONE test for the current voltage at the current temperature(what ever that is) above 2.0v is needed. Applicable to regular evaluation of battery condition ( https://github.com/ruuvi/com.ruuvi.station.ios/issues/836 ) on android, and web as well.

**Comment by rinat-enikeev** [comment]
@DG12 here is the ChatGPT answer :) 


The specific voltage thresholds used in the batteryNeedsReplacement function for the RuuviTag sensors are likely chosen based on the characteristics of the batteries used in these devices and how battery performance varies with temperature.

Battery Chemistry and Performance:

Most small electronic devices like RuuviTags use lithium-ion or lithium-polymer batteries. These battery types have specific discharge characteristics, meaning their ability to deliver power effectively decreases as the voltage drops.
The chosen voltage thresholds (2.3V, 2V, 2.5V) are likely based on the manufacturer's knowledge of the battery's discharge curve and the minimum voltage required for reliable operation and safe firmware updating.
Temperature Impact on Batteries:

Temperature significantly affects battery performance. At lower temperatures, chemical reactions in the battery slow down, reducing the battery's ability to deliver power. This is why lower voltage thresholds are set for colder temperatures.
For temperatures between -20°C and 0°C: The voltage threshold is set to 2.3V. It's slightly lower than the threshold for normal temperatures because the battery's effective capacity is reduced in cold conditions.
For temperatures below -20°C: The threshold is further lowered to 2V, accounting for even more severe impact on battery performance.
For temperatures above 0°C: The threshold is set to 2.5V, which is likely considered a safe minimum for operation and firmware updates under normal conditions.

**Comment by DG12** [comment]
Very cute :^)
Previously known as: "I read it on the internet, it must be true!"

**Comment by DG12** [comment]
Additional thought: 
User should be able to specify the threshold for each sensor since only they know:
1) Critical nature of available data  (set threshold to 1.9 if it is only "nice to know", 2.4 if ruuvi dies and temperature goes out of limit crop is ruined)
2) Difficulty of replacing battery    (set threshold to 2.4 , easy to replace)

**Comment by DG12** [comment]
What was the question you posed to chatGPT?

**Comment by DG12** [comment]
FYI most recent battery failure after 6 months

image

**Pull request merged**
